Repository hashicorp/terraform-provider-aws, pull requests merged in 2018-09, with the labels that each got.

#5753 vendor: aws/aws-sdk-go@v1.15.26
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go
  vendor/github.com/aws/aws-sdk-go/service/eks/api.go
  vendor/github.com/aws/aws-sdk-go/service/eks/doc.go
  vendor/github.com/aws/aws-sdk-go/service/eks/errors.go
  vendor/github.com/aws/aws-sdk-go/service/iot/api.go
  vendor/github.com/aws/aws-sdk-go/service/mediapackage/api.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/api.go
  vendor/github.com/aws/aws-sdk-go/service/sagemaker/api.go
  vendor/github.com/aws/aws-sdk-go/service/waf/api.go
  vendor/github.com/aws/aws-sdk-go/service/waf/errors.go
  vendor/github.com/aws/aws-sdk-go/service/wafregional/api.go
  vendor/github.com/aws/aws-sdk-go/service/wafregional/errors.go
  vendor/vendor.json
Labels: dependencies, provider

#5756 Add example of credit specification block syntax
  website/docs/r/instance.html.markdown
Labels: documentation, service/ec2

#5750 Add unit tests for validate funcs in neptune_event_subscription
  aws/validators_test.go
Labels: service/neptune, tests

#5758 Added ForceNew for aws_redshift_cluster on availability_zone change
  aws/resource_aws_redshift_cluster.go
  aws/resource_aws_redshift_cluster_test.go
Labels: bug, service/redshift

#5749 Add working URL for ICMP types and codes
  aws/resource_aws_network_acl_rule.go
  website/docs/r/default_network_acl.html.markdown
  website/docs/r/network_acl.html.markdown
  website/docs/r/network_acl_rule.html.markdown
Labels: service/ec2

#5755 vendor: hashicorp/go-cleanhttp@v0.5.0
  vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  vendor/github.com/hashicorp/go-cleanhttp/go.mod
  vendor/github.com/hashicorp/go-cleanhttp/handlers.go
  vendor/vendor.json
Labels: dependencies, provider

#5680 Specify to use security group id in aws instance.
  website/docs/r/instance.html.markdown
Labels: documentation, service/ec2

#5776 vendor: jen20/awspolicyequivalence@v1.0.0
  vendor/github.com/jen20/awspolicyequivalence/aws_policy_equivalence.go
  vendor/github.com/jen20/awspolicyequivalence/go.mod
  vendor/github.com/jen20/awspolicyequivalence/go.sum
  vendor/vendor.json
Labels: dependencies, provider

#5777 vendor: Pin hashicorp/logutils@v1.0.0
  vendor/github.com/hashicorp/logutils/go.mod
  vendor/vendor.json
Labels: dependencies, provider

#5778 vendor: Pin hashicorp/go-safetemp@v1.0.0
  vendor/github.com/hashicorp/go-safetemp/go.mod
  vendor/vendor.json
Labels: dependencies, provider

#5779 vendor: Pin mitchellh/go-homedir@v1.0.0
  vendor/github.com/mitchellh/go-homedir/go.mod
  vendor/vendor.json
Labels: dependencies, provider

#5780 vendor: Pin mitchellh/copystructure@v1.0.0 and mitchellh/reflectwalk@v1.0.0
  vendor/github.com/mitchellh/copystructure/go.mod
  vendor/github.com/mitchellh/copystructure/go.sum
  vendor/github.com/mitchellh/reflectwalk/go.mod
  vendor/vendor.json
Labels: dependencies, provider

#5781 vendor: apparentlymart/go-cidr@v1.0.0
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/vendor.json
Labels: dependencies, provider

#5782 vendor: Pin apparentlymart/go-textseg@v1.0.0
  vendor/vendor.json
Labels: dependencies, provider

#5783 vendor: armon/go-radix@v1.0.0
  vendor/github.com/armon/go-radix/go.mod
  vendor/github.com/armon/go-radix/radix.go
  vendor/vendor.json
Labels: dependencies, provider

#5784 vendor: Pin bgentry/speakeasy@v0.1.0
  vendor/vendor.json
Labels: dependencies, provider

#5785 vendor: Pin hashicorp/errwrap@v1.0.0 and hashicorp/go-multierror@v1.0.0
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/go.mod
  vendor/github.com/hashicorp/go-multierror/go.mod
  vendor/github.com/hashicorp/go-multierror/go.sum
  vendor/vendor.json
Labels: dependencies, provider

#5787 vendor: Pin ulikunitz/xz@v0.5.4
  vendor/vendor.json
Labels: dependencies, provider

#5788 vendor: Pin agext/levenshtein@v1.2.1
  vendor/vendor.json
Labels: dependencies, provider

#5793 docs/provider: Update skip_requesting_account_id affected resources
  website/docs/index.html.markdown
Labels: documentation, provider

#5794 provider: WARN log instead of returning error with AWS account ID lookup logic
  aws/config.go
  website/docs/guides/version-2-upgrade.html.md
Labels: bug, provider, regression

#5798 resource/aws_lambda_function: Properly handle `vpc_config` removal
  aws/resource_aws_lambda_function.go
  aws/resource_aws_lambda_function_test.go
Labels: bug, crash, service/lambda

#5792 Fix panic runtime error - aws_lambda_function
  aws/resource_aws_lambda_function.go
Labels: bug, crash, service/lambda

#5797 r/aws_eks_cluster, d/aws_eks_cluster: Add support for EKS Platform Version
  aws/data_source_aws_eks_cluster.go
  aws/data_source_aws_eks_cluster_test.go
  aws/resource_aws_eks_cluster.go
  aws/resource_aws_eks_cluster_test.go
  website/docs/d/eks_cluster.html.markdown
  website/docs/r/eks_cluster.html.markdown
Labels: enhancement, service/eks

#1341 resource/aws_lambda_function: Ignore the VPC configuration if it is empty
  aws/resource_aws_lambda_function.go
  aws/resource_aws_lambda_function_test.go
Labels: bug, service/lambda, size/M

#5801 Data source aws_db_instance: Add enabled_cloudwatch_logs_exports
  aws/data_source_aws_db_instance.go
  aws/data_source_aws_db_instance_test.go
  website/docs/d/db_instance.html.markdown
Labels: enhancement, service/rds

#5627 resource/aws_launch_template: Ensure ebs_optimized argument accepts "unspecified" value
  aws/resource_aws_launch_template.go
  aws/resource_aws_launch_template_test.go
Labels: bug, service/ec2, size/S

#5804 tests/data-source/aws_cloudformation_stack: Fix outputs.VPCId handling for longer VPC IDs
  aws/data_source_aws_cloudformation_stack_test.go
Labels: service/cloudformation, tests

#5641 provider: Add gometalinter to Make targets and additionally enable errcheck, interfacer, and structcheck linting for TravisCI
  .gometalinter.json
  .travis.yml
  GNUmakefile
  scripts/errcheck.sh
  scripts/gofmtcheck.sh
Labels: provider, size/M, tests

#5816 vendor: aws/aws-sdk-go@v1.15.31
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/ec2query/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/query/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/query/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/restjson/restjson.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/restxml/restxml.go
  vendor/github.com/aws/aws-sdk-go/service/apigateway/api.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/api.go
  vendor/github.com/aws/aws-sdk-go/service/cloudtrail/api.go
  vendor/github.com/aws/aws-sdk-go/service/cloudwatchlogs/api.go
  vendor/github.com/aws/aws-sdk-go/service/codecommit/api.go
  vendor/github.com/aws/aws-sdk-go/service/configservice/api.go
  vendor/github.com/aws/aws-sdk-go/service/configservice/errors.go
  vendor/github.com/aws/aws-sdk-go/service/databasemigrationservice/api.go
  vendor/github.com/aws/aws-sdk-go/service/directconnect/api.go
  vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go
  vendor/github.com/aws/aws-sdk-go/service/elastictranscoder/api.go
  vendor/github.com/aws/aws-sdk-go/service/elb/api.go
  vendor/github.com/aws/aws-sdk-go/service/elb/errors.go
  vendor/github.com/aws/aws-sdk-go/service/emr/api.go
  vendor/github.com/aws/aws-sdk-go/service/firehose/api.go
  vendor/github.com/aws/aws-sdk-go/service/iot/api.go
  vendor/github.com/aws/aws-sdk-go/service/lambda/api.go
  vendor/github.com/aws/aws-sdk-go/service/lightsail/api.go
  vendor/github.com/aws/aws-sdk-go/service/mediaconvert/api.go
  vendor/github.com/aws/aws-sdk-go/service/mediapackage/api.go
  vendor/github.com/aws/aws-sdk-go/service/neptune/api.go
  vendor/github.com/aws/aws-sdk-go/service/rds/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/vendor.json
Labels: dependencies, provider, size/XXL

#5828 tests/resource/aws_instance: Add sweeper
  aws/resource_aws_instance.go
  aws/resource_aws_instance_test.go
  aws/resource_aws_spot_instance_request.go
  aws/resource_aws_subnet_test.go
Labels: service/ec2, size/M, tests

#5831 tests/resource/aws_vpn_gateway: Ensure sweeper handles VPC detachment prior to deletion
  aws/resource_aws_vpn_gateway_test.go
Labels: service/ec2, size/M, tests

#5829 tests/resource/aws_lb: Ensure testacc prefix load balancers are included in sweeper
  aws/resource_aws_lb_test.go
Labels: service/elbv2, size/XS, tests

#5825 provider: Fix and enable ineffassign linting
  .gometalinter.json
  aws/cloudfront_distribution_configuration_structure.go
  aws/network_acl_entry.go
  aws/resource_aws_acm_certificate.go
  aws/resource_aws_autoscaling_group_waiting.go
  aws/resource_aws_db_parameter_group.go
  aws/resource_aws_elastic_beanstalk_environment_migrate_test.go
  aws/resource_aws_elasticache_parameter_group.go
  aws/resource_aws_elasticache_replication_group_migrate_test.go
  aws/resource_aws_elb.go
  aws/resource_aws_instance.go
  aws/resource_aws_instance_migrate_test.go
  aws/resource_aws_kinesis_firehose_delivery_stream_migrate_test.go
  aws/resource_aws_load_balancer_policy.go
  aws/resource_aws_neptune_cluster_parameter_group.go
  aws/resource_aws_neptune_parameter_group.go
  aws/resource_aws_rds_cluster.go
  aws/resource_aws_rds_cluster_parameter_group.go
  aws/resource_aws_s3_bucket_inventory.go
  aws/resource_aws_security_group.go
  aws/resource_aws_security_group_migrate_test.go
  aws/resource_aws_ssm_document.go
  aws/resource_aws_volume_attachment_test.go
  aws/resource_aws_waf_regex_match_set_test.go
  aws/resource_aws_waf_rule_group.go
  aws/resource_aws_waf_rule_group_test.go
  aws/resource_aws_wafregional_regex_match_set_test.go
  aws/resource_aws_wafregional_rule_group.go
  aws/resource_aws_wafregional_rule_group_test.go
Labels: provider, size/L, technical-debt

#5823 provider: Fix and enable varcheck linting
  .gometalinter.json
  aws/data_source_aws_vpc_endpoint_service_test.go
  aws/resource_aws_elb_test.go
  aws/resource_aws_iam_access_key_test.go
  aws/resource_aws_route53_record_test.go
  aws/resource_aws_route_test.go
Labels: provider, size/L, technical-debt

#5821 provider: Fix and enable misspell linting for source code and website
  .gometalinter.json
  .travis.yml
  aws/import_aws_security_group.go
  aws/provider.go
  aws/resource_aws_autoscaling_attachment.go
  aws/resource_aws_autoscaling_attachment_test.go
  aws/resource_aws_batch_compute_environment_test.go
  aws/resource_aws_codecommit_trigger.go
  aws/resource_aws_codedeploy_deployment_group_test.go
  aws/resource_aws_cognito_user_pool_test.go
  aws/resource_aws_elasticache_cluster.go
  aws/resource_aws_emr_security_configuration.go
  aws/resource_aws_iam_account_alias_test.go
  aws/resource_aws_iam_user_login_profile.go
  aws/resource_aws_instance.go
  aws/resource_aws_kms_grant.go
  aws/resource_aws_lambda_permission.go
  aws/resource_aws_lightsail_instance.go
  aws/resource_aws_lightsail_key_pair.go
  aws/resource_aws_opsworks_rds_db_instance.go
  aws/resource_aws_route.go
  aws/resource_aws_security_group_rules_matching_test.go
  aws/resource_aws_security_group_test.go
  aws/structure.go
  website/docs/r/codedeploy_deployment_group.html.markdown
  website/docs/r/config_configuration_aggregator.html.markdown
  website/docs/r/db_instance.html.markdown
  website/docs/r/emr_security_configuration.html.markdown
  website/docs/r/lightsail_key_pair.html.markdown
  website/docs/r/ssm_activation.html.markdown
Labels: provider, size/M, technical-debt

#5824 provider: Fix and enable unconvert linting
  .gometalinter.json
  aws/data_source_aws_kms_secret.go
  aws/data_source_aws_kms_secrets.go
  aws/resource_aws_elastic_beanstalk_environment.go
  aws/resource_aws_opsworks_application.go
Labels: provider, size/XS, technical-debt

#5833 Suppress task definition diffs for equivalent port mappings.
  aws/ecs_task_definition_equivalency.go
  aws/ecs_task_definition_equivalency_test.go
  aws/resource_aws_ecs_task_definition.go
  aws/resource_aws_ecs_task_definition_test.go
Labels: enhancement, service/ecs, size/M

#5850 resource/aws_ssm_document: Add support for Session document_type
  aws/resource_aws_ssm_document.go
  aws/resource_aws_ssm_document_test.go
  website/docs/r/ssm_document.html.markdown
Labels: enhancement, service/ssm

#5830 allow ipv4_address_count to be modifiable
  aws/resource_aws_launch_template.go
  aws/resource_aws_launch_template_test.go
  website/docs/r/launch_template.html.markdown
Labels: enhancement, service/ec2, size/S

#5849 [WIP] Issue #4633 retry lambda creation
  aws/resource_aws_lambda_function.go
Labels: bug, service/lambda, size/XS

#5727 resource/aws_ecs_task_definition: Add docker volume configuration
  aws/resource_aws_ecs_task_definition.go
  aws/resource_aws_ecs_task_definition_test.go
  aws/structure.go
  website/docs/r/ecs_task_definition.html.markdown
Labels: enhancement, service/ecs

#5681 Add include body for lambda function association
  aws/cloudfront_distribution_configuration_structure.go
  aws/cloudfront_distribution_configuration_structure_test.go
  aws/resource_aws_cloudfront_distribution.go
  website/docs/r/cloudfront_distribution.html.markdown
Labels: enhancement, service/cloudfront

#5734 Add 'Seperator' property to AWS IoT Firehose Rule
  aws/resource_aws_iot_topic_rule.go
  aws/resource_aws_iot_topic_rule_test.go
  aws/structure.go
  aws/validators.go
  website/docs/r/iot_topic_rule.html.markdown
Labels: enhancement, service/iot

#5737 New Resource: CloudFront Public Key
  aws/provider.go
  aws/resource_aws_cloudfront_public_key.go
  aws/resource_aws_cloudfront_public_key_test.go
  aws/test-fixtures/cloudfront-public-key.pem
  aws/validators.go
  aws/validators_test.go
  website/aws.erb
  website/docs/r/cloudfront_public_key.html.markdown
Labels: new-resource, service/cloudfront, size/L

#5807 Updating elasticsearch resource website documentation. Fixes #5806
  website/docs/r/elasticsearch_domain.html.markdown
  website/docs/r/elasticsearch_domain_policy.html.markdown
Labels: documentation, service/elasticsearch

#5815 Issue #5808 aws_iam_policy does not have a description attribute
  aws/resource_aws_iam_policy.go
  aws/resource_aws_iam_policy_test.go
Labels: bug, service/iam, size/XS

#5817 Issue #5811 Enable x-ray tracing in api_gateway
  aws/resource_aws_api_gateway_stage.go
  aws/resource_aws_api_gateway_stage_test.go
Labels: enhancement, service/apigateway, size/S

#5857 Don't call DeleteUserPermissionsBoundary when deleting a user.
  aws/resource_aws_iam_user.go
Labels: bug, service/iam, size/XS

#5842 resource/aws_s3_bucket: Prevent panics with various API read failures and prevent NoSuchBucket error on deletion
  aws/resource_aws_s3_bucket.go
  aws/resource_aws_s3_bucket_test.go
Labels: bug, crash, service/s3, size/L

#5867 Replace Usage of validateMaxLength() with validation.StringLenBetween()
  aws/data_source_aws_codecommit_repository.go
  aws/data_source_aws_efs_file_system.go
  aws/data_source_aws_iam_server_certificate.go
  aws/resource_aws_appautoscaling_policy.go
  aws/resource_aws_autoscaling_group.go
  aws/resource_aws_cloudwatch_event_rule.go
  aws/resource_aws_cloudwatch_log_metric_filter.go
  aws/resource_aws_codebuild_project.go
  aws/resource_aws_codecommit_repository.go
  aws/resource_aws_codedeploy_deployment_group.go
  aws/resource_aws_cognito_user_group.go
  aws/resource_aws_config_config_rule.go
  aws/resource_aws_config_configuration_aggregator.go
  aws/resource_aws_config_configuration_recorder.go
  aws/resource_aws_config_delivery_channel.go
  aws/resource_aws_efs_file_system.go
  aws/resource_aws_emr_security_configuration.go
  aws/resource_aws_iam_role.go
  aws/resource_aws_iam_server_certificate.go
  aws/resource_aws_iam_user.go
  aws/resource_aws_instance.go
  aws/resource_aws_key_pair.go
  aws/resource_aws_lb_listener_rule.go
  aws/resource_aws_lb_target_group.go
  aws/resource_aws_s3_bucket.go
  aws/resource_aws_s3_bucket_inventory.go
  aws/resource_aws_security_group.go
  aws/resource_aws_servicecatalog_portfolio.go
  aws/resource_aws_ses_template.go
  aws/resource_aws_sfn_activity.go
  aws/resource_aws_sfn_state_machine.go
  aws/resource_aws_waf_rate_based_rule.go
  aws/resource_aws_waf_rule.go
  aws/resource_aws_wafregional_rate_based_rule.go
  aws/validators.go
Labels: provider, size/L, technical-debt

#5870 resource/aws_s3_bucket_inventory: Allow SSE-S3 encryption
  aws/resource_aws_s3_bucket_inventory.go
  aws/resource_aws_s3_bucket_inventory_test.go
  website/docs/r/s3_bucket_inventory.html.markdown
Labels: enhancement, service/s3, size/S

#5852 resource/aws_config_config_rule: Prevent panic when specifying empty scope
  aws/resource_aws_config_config_rule.go
  aws/resource_aws_config_config_rule_test.go
  aws/resource_aws_config_test.go
  aws/structure.go
Labels: bug, crash, service/configservice, size/L

#5837 docs/resource/aws_api_gateway_deployment: Additional information about stage_name argument
  website/docs/r/api_gateway_deployment.html.markdown
Labels: documentation, service/apigateway, size/XS

#5838 tests/resource/aws_vpc: Allow sweeper to handle EC2 eventual consistency
  aws/resource_aws_vpc_test.go
Labels: service/ec2, size/S, tests

#5881 EKS Getting Started: Updates for new AMI naming and bootstrap.sh
  examples/eks-getting-started/eks-worker-nodes.tf
  website/docs/guides/eks-getting-started.html.md
Labels: service/eks, size/M

#5884 resource/aws_iam_policy: Ensure description is properly read during creation
  aws/import_aws_iam_policy_test.go
  aws/provider_test.go
  aws/resource_aws_iam_policy.go
  aws/resource_aws_iam_policy_test.go
Labels: bug, service/iam, size/L

#5886 New resource: aws_dx_bgp_peer
  aws/provider.go
  aws/resource_aws_dx_bgp_peer.go
  aws/resource_aws_dx_bgp_peer_test.go
  website/aws.erb
  website/docs/r/dx_bgp_peer.html.markdown
Labels: new-resource, service/directconnect, size/L

#5894 tests/ec2: Enhance sweepers for VPC deletion
  aws/resource_aws_internet_gateway_test.go
  aws/resource_aws_nat_gateway_test.go
  aws/resource_aws_route_table_test.go
  aws/resource_aws_security_group_test.go
  aws/resource_aws_vpc_test.go
  aws/resource_aws_vpn_gateway_test.go
Labels: service/ec2, size/L, tests

#5900 Update sns_topic_policy.html.markdown
  website/docs/r/sns_topic_policy.html.markdown
Labels: documentation, service/sns, size/XS

#5917 d/aws_cloudwatch_log_group: Reuse existing code to read log group
  aws/data_source_aws_cloudwatch_log_group.go
Labels: service/cloudwatchlogs, size/S, technical-debt

#5916 Allow prefix_list_ids on ingress rules in an aws_security_group
  aws/resource_aws_security_group.go
  aws/resource_aws_security_group_test.go
  website/docs/r/security_group.html.markdown
Labels: documentation, service/ec2, size/L, tests

#5912 Data Source: aws_ami_ids, add sort_ascending flag
  aws/data_source_aws_ami.go
  aws/data_source_aws_ami_ids.go
  aws/data_source_aws_ami_ids_test.go
  aws/sort.go
  website/docs/d/ami_ids.html.markdown
Labels: documentation, enhancement, service/ec2, size/M, tests

#5911 Update elasticache_replication_group documentation
  website/docs/r/elasticache_replication_group.html.markdown
Labels: documentation, service/elasticache, size/XS

#5910 Add import for aws_iam_role_policy_attachment
  aws/resource_aws_iam_role_policy_attachment.go
  aws/resource_aws_iam_role_policy_attachment_test.go
  website/docs/r/iam_role_policy_attachment.markdown
Labels: documentation, service/iam, size/M, tests

#5895 resource/aws_redshift_cluster: Properly disable logging when using logging nested argument
  aws/resource_aws_redshift_cluster.go
Labels: bug, service/redshift, size/M

#5899 tests/resource/aws_security_group: Allow security group rules per group limit to be configurable via environment variable
  aws/resource_aws_security_group_test.go
Labels: service/ec2, size/M, tests

#5931 tests/resource/aws_route_table: Delete Route Table Associations in sweeper
  aws/resource_aws_route_table_test.go
Labels: service/ec2, size/S, tests

#5932 tests/resource/aws_directory_service_directory: Add sweeper
  aws/resource_aws_directory_service_directory.go
  aws/resource_aws_directory_service_directory_test.go
  aws/resource_aws_subnet_test.go
Labels: service/directoryservice, service/ec2, size/L, tests

#5919 tests/provider: Add missing testSweepSkipSweepError() handling
  aws/resource_aws_acmpca_certificate_authority_test.go
  aws/resource_aws_config_aggregate_authorization_test.go
  aws/resource_aws_config_configuration_aggregator_test.go
  aws/resource_aws_config_configuration_recorder_test.go
  aws/resource_aws_config_delivery_channel_test.go
  aws/resource_aws_eks_cluster_test.go
Labels: size/S, tests

#5922 resource/aws_launch_template: Support credit_specification configuration of T3 instance types
  aws/resource_aws_launch_template.go
  aws/resource_aws_launch_template_test.go
Labels: enhancement, service/ec2, size/M, tests

#5936 vendor: aws/aws-sdk-go@v1.15.38
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/cloudwatch/api.go
  vendor/github.com/aws/aws-sdk-go/service/codebuild/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ecs/api.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/api.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/errors.go
  vendor/github.com/aws/aws-sdk-go/service/elasticsearchservice/api.go
  vendor/github.com/aws/aws-sdk-go/service/elastictranscoder/api.go
  vendor/github.com/aws/aws-sdk-go/service/fms/api.go
  vendor/github.com/aws/aws-sdk-go/service/fms/errors.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/api.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/errors.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/aws/aws-sdk-go/service/secretsmanager/api.go
  vendor/github.com/aws/aws-sdk-go/service/ses/api.go
  vendor/vendor.json
Labels: dependencies, size/XXL

#5935 Make use of NewSession() because Session() is deprecated
  aws/resource_aws_instance_test.go
Labels: service/ec2, size/XS, tests

#5766 Add "arns" as an output to "data aws_autoscaling_groups"
  aws/data_source_aws_autoscaling_groups.go
  aws/data_source_aws_autoscaling_groups_test.go
  website/docs/d/autoscaling_groups.html.markdown
Labels: documentation, enhancement, service/autoscaling, service/ec2, size/S, tests

#5939 resource/aws_codebuild_project: Support secondary artifacts and secondary sources
  aws/resource_aws_codebuild_project.go
  aws/resource_aws_codebuild_project_test.go
  website/docs/r/codebuild_project.html.markdown
Labels: documentation, service/codebuild, size/XL, tests

#5941 Updating per #5923
  website/docs/r/instance.html.markdown
Labels: documentation, size/XS

#5771 Update aws_launch_template schema(ipv6 addr count)
  aws/resource_aws_launch_template.go
  aws/resource_aws_launch_template_test.go
Labels: enhancement, service/ec2, size/M, tests

#5944 Update to iam_instance_profile
  website/docs/r/launch_configuration.html.markdown
Labels: documentation, service/ec2, size/XS

#5949 Updated lambda w/ req runtime attr
  website/docs/r/s3_bucket_notification.html.markdown
Labels: documentation, service/s3

#5948 Fix changing engine_version attempts to update resource class
  aws/resource_aws_dms_replication_instance.go
Labels: bug, service/databasemigrationservice

#5957 r/launch_template: fix market options
  aws/resource_aws_launch_template.go
  aws/resource_aws_launch_template_test.go
Labels: bug, service/ec2, size/L, tests

#5968 data-source/aws_ami: Prevent panics with AMIs in failed image state
  aws/data_source_aws_ami.go
  aws/data_source_aws_ami_test.go
Labels: bug, crash, service/ec2, size/S, tests

#5976 resource/aws_rds_cluster: fix the scaling_configuration example value
  website/docs/r/rds_cluster.html.markdown
Labels: documentation, service/rds, size/XS

#5978 vendor: aws/aws-sdk-go@v1.15.41
  vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/directoryservice/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/mediaconvert/api.go
  vendor/github.com/aws/aws-sdk-go/service/rds/api.go
  vendor/github.com/aws/aws-sdk-go/service/rds/errors.go
  vendor/vendor.json
Labels: dependencies, provider, size/XXL

#5980 resource/aws_rds_cluster: Support parallelquery engine_mode
  aws/resource_aws_rds_cluster.go
  aws/resource_aws_rds_cluster_test.go
  website/docs/r/rds_cluster.html.markdown
Labels: documentation, enhancement, service/rds, size/M, tests

#5896 elasticache: Fully expand cluster and replication group resource schemas
  aws/resource_aws_elasticache_cluster.go
  aws/resource_aws_elasticache_replication_group.go
  aws/resource_aws_elasticache_replication_group_test.go
Labels: service/elasticache, size/XL, technical-debt, tests

#5954 resource/aws_dms_replication_instance: Refactor and enhance testing for all attributes
  aws/resource_aws_dms_replication_instance.go
  aws/resource_aws_dms_replication_instance_test.go
Labels: service/databasemigrationservice, size/XL, technical-debt, tests

#5967 resource/aws_launch_template: Properly recreate existing resource when deleted
  aws/resource_aws_launch_template.go
  aws/resource_aws_launch_template_test.go
Labels: bug, service/ec2, size/M, tests

#5972 resource/aws_load_balancer_policy: Properly handle resource when ELB is deleted
  aws/resource_aws_elb_test.go
  aws/resource_aws_load_balancer_policy.go
  aws/resource_aws_load_balancer_policy_test.go
Labels: bug, service/elb, size/L, tests

#5990 resource/aws_ami: Support resource import
  aws/resource_aws_ami.go
  aws/resource_aws_ami_test.go
  website/docs/r/ami.html.markdown
Labels: documentation, enhancement, service/ec2, size/M, tests

#5991 resource/aws_rds_cluster_instance: Properly handle publicly_accessible updates
  aws/resource_aws_rds_cluster_instance.go
  aws/resource_aws_rds_cluster_instance_test.go
Labels: bug, service/rds, size/S, tests

#5995 provider: Ensure validateTypeStringNullableBoolean accepts stringified "true" and "false"
  aws/resource_aws_launch_template_test.go
  aws/validators.go
  aws/validators_test.go
Labels: bug, regression, service/ec2, size/M, tests

#5514 Issue #5374 New Datasource: aws_db_event_categories
  aws/data_source_aws_db_event_categories.go
  aws/data_source_aws_db_event_categories_test.go
  aws/provider.go
  website/aws.erb
  website/docs/d/db_event_categories.html.markdown
Labels: new-data-source, service/rds, size/L

#6000 Add import instructions to Cognito User Pool Client resource documentation
  website/docs/r/cognito_user_pool_client.markdown
Labels: documentation, service/cognito, size/XS

#6002 vendor: aws/aws-sdk-go@v1.15.43
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/restjson/restjson.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/api.go
  vendor/github.com/aws/aws-sdk-go/service/directoryservice/api.go
  vendor/github.com/aws/aws-sdk-go/service/directoryservice/errors.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/glue/api.go
  vendor/github.com/aws/aws-sdk-go/service/rds/api.go
  vendor/github.com/aws/aws-sdk-go/service/sqs/api.go
  vendor/github.com/aws/aws-sdk-go/service/sqs/doc.go
  vendor/github.com/aws/aws-sdk-go/service/sqs/errors.go
  vendor/vendor.json
Labels: dependencies, provider, size/XXL

#5997 Issue #5966 Enable Node-to-Node encryption for Elasticsearch
  aws/resource_aws_elasticsearch_domain.go
  aws/resource_aws_elasticsearch_domain_test.go
  website/docs/r/elasticsearch_domain.html.markdown
Labels: documentation, service/elasticsearch, size/M, tests

#6012 r/resource_aws_rds_cluster: Honor kms_key_id when restoring from snapshot
  aws/resource_aws_rds_cluster.go
  aws/resource_aws_rds_cluster_test.go
Labels: bug, service/rds, size/M, tests

#5982 cloudwatch-event-ecs-target
  aws/resource_aws_cloudwatch_event_target.go
  aws/resource_aws_cloudwatch_event_target_test.go
  website/docs/r/cloudwatch_event_target.html.markdown
Labels: documentation, service/cloudwatchevents, size/M, tests

#6020 adding importing instructions to Cognito User Pool Domains documentation
  website/docs/r/cognito_user_pool_domain.markdown
Labels: documentation, service/cognito, size/XS

#5956 New resource: aws_pinpoint_app
  aws/config.go
  aws/provider.go
  aws/resource_aws_pinpoint_app.go
  aws/resource_aws_pinpoint_app_test.go
  aws/test-fixtures/lambdapinpoint.zip
  website/aws.erb
  website/docs/r/pinpoint_app.markdown
Labels: documentation, service/pinpoint, size/XL, tests, waiting-response

#5827 codedeploy_deployment_group: Include autoscaling groups when updating blue green config.
  aws/resource_aws_codedeploy_deployment_group.go
  aws/resource_aws_codedeploy_deployment_group_test.go
Labels: bug, service/codedeploy, size/L
